/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author T Amaradeepan
 */
public class Records extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    /**
     * Creates new form StudentRecord
     */
    public Records() {
        initComponents();
        con=Connect.ConnectDB();
        Get_Data();
        setLocationRelativeTo(null);
    }
    
    private void Get_Data(){
        String sql="SELECT * FROM drone";
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            dataTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        pilotrecord = new javax.swing.JButton();
        unitofficerrecord = new javax.swing.JButton();
        pilotform = new javax.swing.JButton();
        unitofficerform = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        printjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Record");

        dataTable.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14"
            }
        ));
        dataTable.setMaximumSize(new java.awt.Dimension(1600, 900));
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        pilotrecord.setText("Pilot Record");
        pilotrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilotrecordActionPerformed(evt);
            }
        });

        unitofficerrecord.setText("Unit Officer Record");
        unitofficerrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitofficerrecordActionPerformed(evt);
            }
        });

        pilotform.setText("Pilot Form");
        pilotform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilotformActionPerformed(evt);
            }
        });

        unitofficerform.setText("Unit Officer Form");
        unitofficerform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitofficerformActionPerformed(evt);
            }
        });

        jButton11.setText("Logout");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        backButton.setText("Main Menu");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        printjButton.setText("Print");
        printjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(backButton)
                .addGap(77, 77, 77)
                .addComponent(pilotrecord)
                .addGap(68, 68, 68)
                .addComponent(unitofficerrecord)
                .addGap(57, 57, 57)
                .addComponent(pilotform)
                .addGap(42, 42, 42)
                .addComponent(unitofficerform)
                .addGap(42, 42, 42)
                .addComponent(jButton11)
                .addGap(52, 52, 52)
                .addComponent(printjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {backButton, jButton11, pilotform, pilotrecord, unitofficerform, unitofficerrecord});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilotrecord)
                    .addComponent(backButton)
                    .addComponent(unitofficerrecord)
                    .addComponent(pilotform)
                    .addComponent(unitofficerform)
                    .addComponent(jButton11)
                    .addComponent(printjButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        try{
            con = Connect.ConnectDB();
            int row = dataTable.getSelectedRow();
            String tableClick = dataTable.getModel().getValueAt(row, 0).toString();
            String sql = "select * from drone where Model= "+tableClick;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                this.hide();
                UAVDetails drone=new UAVDetails();
                drone.setVisible(true);
                String add1 = rs.getString("Model");
                drone.p2.setText(add1);
                String add2 = rs.getString("Name");
                drone.p1.setText(add2);
                String add3 = rs.getString("Use");
                drone.p3.setText(add3);
                String add4 = rs.getString("Wingspan");
                drone.p4.setText(add4);
                String add5 = rs.getString("Length");
                drone.p5.setText(add5);
                String add6 = rs.getString("Weight");
                drone.p6.setText(add6);
                String add7 = rs.getString("Flightcontrol");
                drone.p7.setText(add7);
                String add8 = rs.getString("Level");
                drone.p8.setSelectedItem(add8);
                String add9 = rs.getString("Altitude");
                drone.p9.setText(add9);
                String add10 = rs.getString("Cruisespeed");
                drone.p10.setText(add10);
                String add11 = rs.getString("Dashspeed");
                drone.p11.setText(add11);
                String add12 = rs.getString("AadharNumber");
                drone.p12.setText(add12);
                String add13 = rs.getString("Payloadoptions");
                drone.p13.setText(add13);
                String add14 = rs.getString("Endurance");
                drone.p14.setText(add14);
                drone.updateButton.setEnabled(true);
                drone.deleteButton.setEnabled(true);
                drone.saveButton.setEnabled(true);
                //student.studentIdField.setEnabled(true);
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_dataTableMouseClicked

    private void pilotrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilotrecordActionPerformed
        Record2 record=new Record2();
        this.hide();
        record.setVisible(true);
    }//GEN-LAST:event_pilotrecordActionPerformed

    private void unitofficerrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitofficerrecordActionPerformed
        PilotRecord record=new PilotRecord();
        this.hide();
        record.setVisible(true);
    }//GEN-LAST:event_unitofficerrecordActionPerformed

    private void pilotformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilotformActionPerformed
        PilotDetails form=new PilotDetails();
        this.hide();
        form.setVisible(true);
    }//GEN-LAST:event_pilotformActionPerformed

    private void unitofficerformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitofficerformActionPerformed
        UnitOfficerform form=new UnitOfficerform();
        this.hide();
        form.setVisible(true);
    }//GEN-LAST:event_unitofficerformActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Login login=new Login();
        this.hide();
        login.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        /*StudentForm menu=new StudentForm();
        this.hide();
        menu.setVisible(true);*/
        MainMenu m=new MainMenu();
        m.setVisible(true);
        this.hide();
    }//GEN-LAST:event_backButtonActionPerformed

    private void printjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printjButtonActionPerformed
        // TODO add your handling code here:
        try {
            boolean print = dataTable.print();
            if (!print) {
                JOptionPane.showMessageDialog(null, "Unable To Print !!..");
            }
        }
        catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_printjButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
    this.hide();
    UAVDetails form = new UAVDetails();
    form.setVisible(true);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Records().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton jButton11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pilotform;
    private javax.swing.JButton pilotrecord;
    private javax.swing.JButton printjButton;
    private javax.swing.JButton unitofficerform;
    private javax.swing.JButton unitofficerrecord;
    // End of variables declaration//GEN-END:variables
}
